"""create steps table

Revision ID: 29305d8af6d3
Revises: f94ad8943fb1
Create Date: 2022-08-31 04:33:26.525583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29305d8af6d3'
down_revision = 'f94ad8943fb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('steps')
    # ### end Alembic commands ###
