"""empty message

Revision ID: 475f9b3c2939
Revises: ffdc0a98111c
Create Date: 2022-08-30 18:26:28.799359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475f9b3c2939'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=50), nullable=True))
    # op.alter_column('users', 'first_name', nullable=False)
    # op.alter_column('users', 'last_name', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
